apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: npwd-deployment
spec:
  selector:
    matchLabels:
      app: npwd
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: npwd
    spec:
      containers:
      - name: npwd
        image: anandshivasingh/npwd:1.0.#{Build.BuildId}#
        ports:
        - containerPort: 80
        env:
          - name: ConnectionStrings
            valueFrom:
              secretKeyRef:
                name: mssql-secret
                key: db-connection-string-secret

---
kind: Service
apiVersion: v1
metadata:
  name: npwd-service
spec:
  selector:
    app: npwd
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer